In [10]:
import pandas as pd
# load df:

df = pd.read_csv("housing_modified.csv")

In [11]:
# Bedrooms compared to total rooms
df["bedrooms_to_rooms_ratio"] = df["total_bedrooms"] / df["total_rooms"]

# Households compared to population
df["households_to_population_ratio"] = df["households"] / df["population"]

# View the new features
df.head()

,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,distance_to_nearest_city,ocean_proximity_<1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,bedrooms_to_rooms_ratio,households_to_population_ratio
0,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,20.33,0,0,0,1,0.146591,0.391304
1,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,19.91,0,0,0,1,0.155797,0.473969
2,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,17.84,0,0,0,1,0.129516,0.356855
3,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,17.06,0,0,0,1,0.184458,0.392473
4,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,17.06,0,0,0,1,0.172096,0.458407

In [12]:
# I will drop "total_bedrooms" and "households" as they are now represented in the new features:
df = df.drop(["total_bedrooms", "households"], axis=1)

In [13]:
df.head()

,housing_median_age,total_rooms,population,median_income,median_house_value,distance_to_nearest_city,ocean_proximity_<1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,bedrooms_to_rooms_ratio,households_to_population_ratio
0,41.0,880.0,322.0,8.3252,452600.0,20.33,0,0,0,1,0.146591,0.391304
1,21.0,7099.0,2401.0,8.3014,358500.0,19.91,0,0,0,1,0.155797,0.473969
2,52.0,1467.0,496.0,7.2574,352100.0,17.84,0,0,0,1,0.129516,0.356855
3,52.0,1274.0,558.0,5.6431,341300.0,17.06,0,0,0,1,0.184458,0.392473
4,52.0,1627.0,565.0,3.8462,342200.0,17.06,0,0,0,1,0.172096,0.458407

In [14]:
# now i will run again selectKBest tool to see if the new features are selected as important or not.
from sklearn.feature_selection import SelectKBest, f_regression

X = df.drop("median_house_value", axis=1)
y = df["median_house_value"]

In [15]:
# Apply SelectKBest:
# same number RFE selected - 7 so i can compare results.
selector = SelectKBest(score_func=f_regression, k=7)

X_selected = selector.fit_transform(X, y)

In [16]:
# Get feature scores
#the results are very similar 
scores = pd.DataFrame({
    "Feature": X.columns,
    "Score": selector.scores_
})

scores = scores.sort_values(by="Score", ascending=False)

print(scores)

                           Feature         Score
3                    median_income  18398.896423
6           ocean_proximity_INLAND   6276.831559
4         distance_to_nearest_city   4734.241478
10  households_to_population_ratio   1535.052213
5        ocean_proximity_<1H OCEAN   1452.289249
9          bedrooms_to_rooms_ratio   1431.435320
8         ocean_proximity_NEAR BAY    540.400961
1                      total_rooms    369.570525
0               housing_median_age    234.089601
2                       population     13.085778
7           ocean_proximity_ISLAND     11.313389

In [17]:
# Save the updated dataframe with ratio features
df.to_csv("housing_with_ratio_features.csv", index=False)