### I already converted the dataset into numeric format. We be used reduced dataset

In [6]:
import pandas as pd
from mlxtend.frequent_patterns import apriori

df = pd.read_csv("mushroom_reduced.csv")
df.head()

,class,does-bruise-or-bleed,stem-height,stem-width,cap-surface_d,cap-surface_e,cap-surface_g,cap-surface_h,cap-surface_i,cap-surface_k,...,stem-color_g,stem-color_k,stem-color_l,stem-color_n,stem-color_o,stem-color_p,stem-color_r,stem-color_u,stem-color_w,stem-color_y
0,1,0,16.95,17.09,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,0,17.99,18.19,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,1,0,17.80,17.74,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,0,15.77,15.98,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
4,1,0,16.53,17.20,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0

In [7]:
df.columns

Index(['class', 'does-bruise-or-bleed', 'stem-height', 'stem-width',
       'cap-surface_d', 'cap-surface_e', 'cap-surface_g', 'cap-surface_h',
       'cap-surface_i', 'cap-surface_k', 'cap-surface_l',
       'cap-surface_missing', 'cap-surface_s', 'cap-surface_t',
       'cap-surface_w', 'cap-surface_y', 'gill-attachment_a',
       'gill-attachment_d', 'gill-attachment_e', 'gill-attachment_f',
       'gill-attachment_missing', 'gill-attachment_p', 'gill-attachment_s',
       'gill-attachment_x', 'gill-spacing_c', 'gill-spacing_d',
       'gill-spacing_f', 'gill-spacing_missing', 'gill-color_b',
       'gill-color_e', 'gill-color_f', 'gill-color_g', 'gill-color_k',
       'gill-color_n', 'gill-color_o', 'gill-color_p', 'gill-color_r',
       'gill-color_u', 'gill-color_w', 'gill-color_y', 'stem-color_b',
       'stem-color_e', 'stem-color_f', 'stem-color_g', 'stem-color_k',
       'stem-color_l', 'stem-color_n', 'stem-color_o', 'stem-color_p',
       'stem-color_r', 'stem-color_u', 'stem-color_w', 'stem-color_y'],
      dtype='object')

In [8]:
category_columns = ['does-bruise-or-bleed',
       'cap-surface_d', 'cap-surface_e', 'cap-surface_g', 'cap-surface_h',
       'cap-surface_i', 'cap-surface_k', 'cap-surface_l',
       'cap-surface_missing', 'cap-surface_s', 'cap-surface_t',
       'cap-surface_w', 'cap-surface_y', 'gill-attachment_a',
       'gill-attachment_d', 'gill-attachment_e', 'gill-attachment_f',
       'gill-attachment_missing', 'gill-attachment_p', 'gill-attachment_s',
       'gill-attachment_x', 'gill-spacing_c', 'gill-spacing_d',
       'gill-spacing_f', 'gill-spacing_missing', 'gill-color_b',
       'gill-color_e', 'gill-color_f', 'gill-color_g', 'gill-color_k',
       'gill-color_n', 'gill-color_o', 'gill-color_p', 'gill-color_r',
       'gill-color_u', 'gill-color_w', 'gill-color_y', 'stem-color_b',
       'stem-color_e', 'stem-color_f', 'stem-color_g', 'stem-color_k',
       'stem-color_l', 'stem-color_n', 'stem-color_o', 'stem-color_p',
       'stem-color_r', 'stem-color_u', 'stem-color_w', 'stem-color_y']

# this has to be a version of the DataFrame
# with only categorical values in numeric format
categories_only_df = df[category_columns]

# Use apriori to find itemsets with low support
# use encoders and other means to convert everything to numeric format
# see lecture notes later for how this was done on this particular dataset 
# (lifestyle_sustainability_data.csv)
frequent_itemsets = apriori(categories_only_df, min_support=0.0001, use_colnames=True)

# Filter for itemsets with low support, and sort by lowest score
# adjust the the decimal to increase or decrease threshold

# adjust threshold if nothing shows up (increase)
rare_itemsets = frequent_itemsets[frequent_itemsets['support'] < 0.003]
rare_itemsets.sort_values("support")

# based on this result, DietType and Gender might have balancing issues in the dataset, 
# check manually with seaborn that there's enough data for each combination!  
# Also HomeType + Gender can have balancing issues (if any)

# look at this in DataWrangler for better details
rare_itemsets

c:\Storage\Studies\Lapland_AMK\5_semester\Advanced Data Analytics\venv312\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

       support                                           itemsets
37    0.002833                                     (stem-color_b)
78    0.002882               (does-bruise-or-bleed, gill-color_u)
92    0.002849                 (cap-surface_d, gill-attachment_s)
97    0.001359                      (gill-color_b, cap-surface_d)
98    0.001818                      (gill-color_e, cap-surface_d)
...        ...                                                ...
5993  0.002882  (does-bruise-or-bleed, gill-color_w, cap-surfa...
5994  0.001539  (gill-attachment_missing, does-bruise-or-bleed...
5995  0.001326  (gill-attachment_missing, does-bruise-or-bleed...
5996  0.001506  (gill-attachment_missing, does-bruise-or-bleed...
5997  0.001408  (gill-attachment_missing, does-bruise-or-bleed...

[3541 rows x 2 columns]