In [174]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [175]:
# load the dataset:
df = pd.read_csv("mushroom.csv")
df.head()

,class,cap-diameter,cap-shape,cap-surface,cap-color,does-bruise-or-bleed,gill-attachment,gill-spacing,gill-color,stem-height,...,stem-root,stem-surface,stem-color,veil-type,veil-color,has-ring,ring-type,spore-print-color,habitat,season
0,p,15.26,x,g,o,f,e,NaN,w,16.95,...,s,y,w,u,w,t,g,NaN,d,w
1,p,16.60,x,g,o,f,e,NaN,w,17.99,...,s,y,w,u,w,t,g,NaN,d,u
2,p,14.07,x,g,o,f,e,NaN,w,17.80,...,s,y,w,u,w,t,g,NaN,d,w
3,p,14.17,f,h,e,f,e,NaN,w,15.77,...,s,y,w,u,w,t,p,NaN,d,w
4,p,14.64,x,h,o,f,e,NaN,w,16.53,...,s,y,w,u,w,t,p,NaN,d,w

In [176]:
df.describe()

       cap-diameter   stem-height    stem-width
count  61069.000000  61069.000000  61069.000000
mean       6.733854      6.581538     12.149410
std        5.264845      3.370017     10.035955
min        0.380000      0.000000      0.000000
25%        3.480000      4.640000      5.210000
50%        5.860000      5.950000     10.190000
75%        8.540000      7.740000     16.570000
max       62.340000     33.920000    103.910000

In [177]:
df.columns.tolist()

['class',
 'cap-diameter',
 'cap-shape',
 'cap-surface',
 'cap-color',
 'does-bruise-or-bleed',
 'gill-attachment',
 'gill-spacing',
 'gill-color',
 'stem-height',
 'stem-width',
 'stem-root',
 'stem-surface',
 'stem-color',
 'veil-type',
 'veil-color',
 'has-ring',
 'ring-type',
 'spore-print-color',
 'habitat',
 'season']

In [178]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61069 entries, 0 to 61068
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   class                 61069 non-null  object
 1   cap-diameter          61069 non-null  float64
 2   cap-shape             61069 non-null  object
 3   cap-surface           46949 non-null  object
 4   cap-color             61069 non-null  object
 5   does-bruise-or-bleed  61069 non-null  object
 6   gill-attachment       51185 non-null  object
 7   gill-spacing          36006 non-null  object
 8   gill-color            61069 non-null  object
 9   stem-height           61069 non-null  float64
 10  stem-width            61069 non-null  float64
 11  stem-root             9531 non-null   object
 12  stem-surface          22945 non-null  object
 13  stem-color            61069 non-null  object
 14  veil-type             3177 non-null   object
 15  veil-color            7413 non-null   object
 16  has-ring              61069 non-null  object
 17  ring-type             58598 non-null  object
 18  spore-print-color     6354 non-null   object
 19  habitat               61069 non-null  object
 20  season                61069 non-null  object
dtypes: float64(3), object(18)
memory usage: 9.8+ MB

In [179]:
df.isnull().sum()

class                       0
cap-diameter                0
cap-shape                   0
cap-surface             14120
cap-color                   0
does-bruise-or-bleed        0
gill-attachment          9884
gill-spacing            25063
gill-color                  0
stem-height                 0
stem-width                  0
stem-root               51538
stem-surface            38124
stem-color                  0
veil-type               57892
veil-color              53656
has-ring                    0
ring-type                2471
spore-print-color       54715
habitat                     0
season                      0
dtype: int64

In [180]:
cols = df.columns.tolist()

for col in cols:
    unique_count = df[col].nunique()
    print(f'{col} has {unique_count} unique values')

class has 2 unique values
cap-diameter has 2571 unique values
cap-shape has 7 unique values
cap-surface has 11 unique values
cap-color has 12 unique values
does-bruise-or-bleed has 2 unique values
gill-attachment has 7 unique values
gill-spacing has 3 unique values
gill-color has 12 unique values
stem-height has 2226 unique values
stem-width has 4630 unique values
stem-root has 5 unique values
stem-surface has 8 unique values
stem-color has 13 unique values
veil-type has 1 unique values
veil-color has 6 unique values
has-ring has 2 unique values
ring-type has 8 unique values
spore-print-color has 7 unique values
habitat has 8 unique values
season has 4 unique values

In [181]:
for col in cols:
    unique_name = df[col].unique()
    print(f'{col} has {unique_name}')

class has ['p' 'e']
cap-diameter has [15.26 16.6  14.07 ... 22.85 21.8  20.42]
cap-shape has ['x' 'f' 'p' 'b' 'c' 's' 'o']
cap-surface has ['g' 'h' nan 't' 'y' 'e' 's' 'l' 'd' 'w' 'i' 'k']
cap-color has ['o' 'e' 'n' 'g' 'r' 'w' 'y' 'p' 'u' 'b' 'l' 'k']
does-bruise-or-bleed has ['f' 't']
gill-attachment has ['e' nan 'a' 'd' 's' 'x' 'p' 'f']
gill-spacing has [nan 'c' 'd' 'f']
gill-color has ['w' 'n' 'p' 'u' 'b' 'g' 'y' 'r' 'e' 'o' 'k' 'f']
stem-height has [16.95 17.99 17.8  ...  1.23  1.16  0.  ]
stem-width has [17.09 18.19 17.74 ... 32.59 30.99 30.51]
stem-root has ['s' nan 'b' 'r' 'c' 'f']
stem-surface has ['y' nan 's' 'k' 'i' 'h' 't' 'g' 'f']
stem-color has ['w' 'y' 'n' 'u' 'b' 'l' 'r' 'p' 'e' 'k' 'g' 'o' 'f']
veil-type has ['u' nan]
veil-color has ['w' 'y' nan 'n' 'e' 'u' 'k']
has-ring has ['t' 'f']
ring-type has ['g' 'p' 'e' 'l' 'f' 'm' nan 'r' 'z']
spore-print-color has [nan 'w' 'p' 'k' 'r' 'u' 'n' 'g']
habitat has ['d' 'm' 'g' 'h' 'l' 'p' 'w' 'u']
season has ['w' 'u' 'a' 's']

In [182]:
# List of columns to drop
cols_to_drop = ['stem-root', 'spore-print-color', 'veil-color',"veil-type",'stem-surface']

# Drop them from the dataset
df = df.drop(columns=cols_to_drop)

In [183]:
df.head()

,class,cap-diameter,cap-shape,cap-surface,cap-color,does-bruise-or-bleed,gill-attachment,gill-spacing,gill-color,stem-height,stem-width,stem-color,has-ring,ring-type,habitat,season
0,p,15.26,x,g,o,f,e,NaN,w,16.95,17.09,w,t,g,d,w
1,p,16.60,x,g,o,f,e,NaN,w,17.99,18.19,w,t,g,d,u
2,p,14.07,x,g,o,f,e,NaN,w,17.80,17.74,w,t,g,d,w
3,p,14.17,f,h,e,f,e,NaN,w,15.77,15.98,w,t,p,d,w
4,p,14.64,x,h,o,f,e,NaN,w,16.53,17.20,w,t,p,d,w

In [184]:
# Check number of duplicates
print("Duplicates found:", df.duplicated().sum())

# View some duplicate rows
df[df.duplicated()].head()

Duplicates found: 146

,class,cap-diameter,cap-shape,cap-surface,cap-color,does-bruise-or-bleed,gill-attachment,gill-spacing,gill-color,stem-height,stem-width,stem-color,has-ring,ring-type,habitat,season
9863,p,1.14,x,g,w,f,a,d,w,3.13,1.78,e,f,f,d,u
12978,p,0.72,x,g,y,f,NaN,NaN,y,3.51,0.77,y,f,f,d,u
56526,p,4.27,o,s,n,f,NaN,c,w,0.00,0.00,f,f,f,d,u
56533,p,4.29,o,t,w,f,NaN,c,w,0.00,0.00,f,f,f,d,u
56576,p,4.59,o,s,w,f,NaN,c,w,0.00,0.00,f,f,f,d,u

In [185]:
# Code to fill missing values with "missing"
# List of target columns
cols_to_fill = ['cap-surface', 'gill-attachment', 'gill-spacing', 'ring-type']
df[cols_to_fill] = df[cols_to_fill].fillna('missing')

In [186]:
df.isnull().sum()

class                   0
cap-diameter            0
cap-shape               0
cap-surface             0
cap-color               0
does-bruise-or-bleed    0
gill-attachment         0
gill-spacing            0
gill-color              0
stem-height             0
stem-width              0
stem-color              0
has-ring                0
ring-type               0
habitat                 0
season                  0
dtype: int64

In [187]:
cols = df.columns.tolist()

for col in cols:
    unique_count = df[col].nunique()
    print(f'{col} has {unique_count} unique values')

class has 2 unique values
cap-diameter has 2571 unique values
cap-shape has 7 unique values
cap-surface has 12 unique values
cap-color has 12 unique values
does-bruise-or-bleed has 2 unique values
gill-attachment has 8 unique values
gill-spacing has 4 unique values
gill-color has 12 unique values
stem-height has 2226 unique values
stem-width has 4630 unique values
stem-color has 13 unique values
has-ring has 2 unique values
ring-type has 9 unique values
habitat has 8 unique values
season has 4 unique values

In [188]:
# here I will encode the categorical variables using one-hot encoding
# Copy the dataset
df_encoded = df.copy()

# Columns to encode
numeric_features = ['cap-diameter', 'stem-height', 'stem-width']
binary_categorical = ["class",'does-bruise-or-bleed', 'has-ring']
onehot_categorical = ['cap-shape', 'cap-surface', 'cap-color', 'gill-attachment',
                      'gill-spacing', 'gill-color', 'stem-color', 'ring-type',
                      'habitat', 'season']

In [189]:
from sklearn.preprocessing import OneHotEncoder

variables_oneHot_cat = onehot_categorical

# use encoder:
encoder = OneHotEncoder(sparse_output=False).set_output(transform="pandas")
one_hot_encoded = encoder.fit_transform(df_encoded[variables_oneHot_cat]).astype(int)


df_encoded = pd.concat([df_encoded,one_hot_encoded],axis=1).drop(columns=variables_oneHot_cat)

In [190]:
df_encoded.head()

,class,cap-diameter,does-bruise-or-bleed,stem-height,stem-width,has-ring,cap-shape_b,cap-shape_c,cap-shape_f,cap-shape_o,...,habitat_h,habitat_l,habitat_m,habitat_p,habitat_u,habitat_w,season_a,season_s,season_u,season_w
0,p,15.26,f,16.95,17.09,t,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,p,16.60,f,17.99,18.19,t,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,p,14.07,f,17.80,17.74,t,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,p,14.17,f,15.77,15.98,t,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
4,p,14.64,f,16.53,17.20,t,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [191]:
zero_only_columns = one_hot_encoded.columns[(one_hot_encoded.sum(axis=0) == 0)]
print(zero_only_columns)

Index([], dtype='object')

In [192]:
from sklearn.preprocessing import LabelEncoder

# list of all boolean variables we want to convert
variables_label_Encode = binary_categorical

# initalize encoder and convert everything
encoder = LabelEncoder()
df_encoded[variables_label_Encode] = df_encoded[variables_label_Encode].apply(encoder.fit_transform)

In [193]:
df_encoded.head()

,class,cap-diameter,does-bruise-or-bleed,stem-height,stem-width,has-ring,cap-shape_b,cap-shape_c,cap-shape_f,cap-shape_o,...,habitat_h,habitat_l,habitat_m,habitat_p,habitat_u,habitat_w,season_a,season_s,season_u,season_w
0,1,15.26,0,16.95,17.09,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,1,16.60,0,17.99,18.19,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,1,14.07,0,17.80,17.74,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,1,14.17,0,15.77,15.98,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
4,1,14.64,0,16.53,17.20,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [194]:
cols = df_encoded.columns.tolist()
print(cols)

['class', 'cap-diameter', 'does-bruise-or-bleed', 'stem-height', 'stem-width', 'has-ring', 'cap-shape_b', 'cap-shape_c', 'cap-shape_f', 'cap-shape_o', 'cap-shape_p', 'cap-shape_s', 'cap-shape_x', 'cap-surface_d', 'cap-surface_e', 'cap-surface_g', 'cap-surface_h', 'cap-surface_i', 'cap-surface_k', 'cap-surface_l', 'cap-surface_missing', 'cap-surface_s', 'cap-surface_t', 'cap-surface_w', 'cap-surface_y', 'cap-color_b', 'cap-color_e', 'cap-color_g', 'cap-color_k', 'cap-color_l', 'cap-color_n', 'cap-color_o', 'cap-color_p', 'cap-color_r', 'cap-color_u', 'cap-color_w', 'cap-color_y', 'gill-attachment_a', 'gill-attachment_d', 'gill-attachment_e', 'gill-attachment_f', 'gill-attachment_missing', 'gill-attachment_p', 'gill-attachment_s', 'gill-attachment_x', 'gill-spacing_c', 'gill-spacing_d', 'gill-spacing_f', 'gill-spacing_missing', 'gill-color_b', 'gill-color_e', 'gill-color_f', 'gill-color_g', 'gill-color_k', 'gill-color_n', 'gill-color_o', 'gill-color_p', 'gill-color_r', 'gill-color_u', 'gill-color_w', 'gill-color_y', 'stem-color_b', 'stem-color_e', 'stem-color_f', 'stem-color_g', 'stem-color_k', 'stem-color_l', 'stem-color_n', 'stem-color_o', 'stem-color_p', 'stem-color_r', 'stem-color_u', 'stem-color_w', 'stem-color_y', 'ring-type_e', 'ring-type_f', 'ring-type_g', 'ring-type_l', 'ring-type_m', 'ring-type_missing', 'ring-type_p', 'ring-type_r', 'ring-type_z', 'habitat_d', 'habitat_g', 'habitat_h', 'habitat_l', 'habitat_m', 'habitat_p', 'habitat_u', 'habitat_w', 'season_a', 'season_s', 'season_u', 'season_w']

In [195]:
cols = df_encoded.columns.tolist()

for col in cols:
    unique_count = df_encoded[col].nunique()
    print(f'{col} has {unique_count} unique values')

class has 2 unique values
cap-diameter has 2571 unique values
does-bruise-or-bleed has 2 unique values
stem-height has 2226 unique values
stem-width has 4630 unique values
has-ring has 2 unique values
cap-shape_b has 2 unique values
cap-shape_c has 2 unique values
cap-shape_f has 2 unique values
cap-shape_o has 2 unique values
cap-shape_p has 2 unique values
cap-shape_s has 2 unique values
cap-shape_x has 2 unique values
cap-surface_d has 2 unique values
cap-surface_e has 2 unique values
cap-surface_g has 2 unique values
cap-surface_h has 2 unique values
cap-surface_i has 2 unique values
cap-surface_k has 2 unique values
cap-surface_l has 2 unique values
cap-surface_missing has 2 unique values
cap-surface_s has 2 unique values
cap-surface_t has 2 unique values
cap-surface_w has 2 unique values
cap-surface_y has 2 unique values
cap-color_b has 2 unique values
cap-color_e has 2 unique values
cap-color_g has 2 unique values
cap-color_k has 2 unique values
cap-color_l has 2 unique values
cap-color_n has 2 unique values
cap-color_o has 2 unique values
cap-color_p has 2 unique values
cap-color_r has 2 unique values
cap-color_u has 2 unique values
cap-color_w has 2 unique values
cap-color_y has 2 unique values
gill-attachment_a has 2 unique values
gill-attachment_d has 2 unique values
gill-attachment_e has 2 unique values
gill-attachment_f has 2 unique values
gill-attachment_missing has 2 unique values
gill-attachment_p has 2 unique values
gill-attachment_s has 2 unique values
gill-attachment_x has 2 unique values
gill-spacing_c has 2 unique values
gill-spacing_d has 2 unique values
gill-spacing_f has 2 unique values
gill-spacing_missing has 2 unique values
gill-color_b has 2 unique values
gill-color_e has 2 unique values
gill-color_f has 2 unique values
gill-color_g has 2 unique values
gill-color_k has 2 unique values
gill-color_n has 2 unique values
gill-color_o has 2 unique values
gill-color_p has 2 unique values
gill-color_r has 2 unique values
gill-color_u has 2 unique values
gill-color_w has 2 unique values
gill-color_y has 2 unique values
stem-color_b has 2 unique values
stem-color_e has 2 unique values
stem-color_f has 2 unique values
stem-color_g has 2 unique values
stem-color_k has 2 unique values
stem-color_l has 2 unique values
stem-color_n has 2 unique values
stem-color_o has 2 unique values
stem-color_p has 2 unique values
stem-color_r has 2 unique values
stem-color_u has 2 unique values
stem-color_w has 2 unique values
stem-color_y has 2 unique values
ring-type_e has 2 unique values
ring-type_f has 2 unique values
ring-type_g has 2 unique values
ring-type_l has 2 unique values
ring-type_m has 2 unique values
ring-type_missing has 2 unique values
ring-type_p has 2 unique values
ring-type_r has 2 unique values
ring-type_z has 2 unique values
habitat_d has 2 unique values
habitat_g has 2 unique values
habitat_h has 2 unique values
habitat_l has 2 unique values
habitat_m has 2 unique values
habitat_p has 2 unique values
habitat_u has 2 unique values
habitat_w has 2 unique values
season_a has 2 unique values
season_s has 2 unique values
season_u has 2 unique values
season_w has 2 unique values

In [196]:
df_encoded.isnull().sum()

class                   0
cap-diameter            0
does-bruise-or-bleed    0
stem-height             0
stem-width              0
                       ..
habitat_w               0
season_a                0
season_s                0
season_u                0
season_w                0
Length: 95, dtype: int64

In [197]:
df_encoded.to_csv("mushroom_encoded.csv", index=False)