In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# load the dataset:
df = pd.read_csv("mushroom.csv")
df.head()

,class,cap-diameter,cap-shape,cap-surface,cap-color,does-bruise-or-bleed,gill-attachment,gill-spacing,gill-color,stem-height,...,stem-root,stem-surface,stem-color,veil-type,veil-color,has-ring,ring-type,spore-print-color,habitat,season
0,p,15.26,x,g,o,f,e,NaN,w,16.95,...,s,y,w,u,w,t,g,NaN,d,w
1,p,16.60,x,g,o,f,e,NaN,w,17.99,...,s,y,w,u,w,t,g,NaN,d,u
2,p,14.07,x,g,o,f,e,NaN,w,17.80,...,s,y,w,u,w,t,g,NaN,d,w
3,p,14.17,f,h,e,f,e,NaN,w,15.77,...,s,y,w,u,w,t,p,NaN,d,w
4,p,14.64,x,h,o,f,e,NaN,w,16.53,...,s,y,w,u,w,t,p,NaN,d,w

In [4]:
df.describe()

       cap-diameter   stem-height    stem-width
count  61069.000000  61069.000000  61069.000000
mean       6.733854      6.581538     12.149410
std        5.264845      3.370017     10.035955
min        0.380000      0.000000      0.000000
25%        3.480000      4.640000      5.210000
50%        5.860000      5.950000     10.190000
75%        8.540000      7.740000     16.570000
max       62.340000     33.920000    103.910000

In [9]:
df.columns.tolist()

['class',
 'cap-diameter',
 'cap-shape',
 'cap-surface',
 'cap-color',
 'does-bruise-or-bleed',
 'gill-attachment',
 'gill-spacing',
 'gill-color',
 'stem-height',
 'stem-width',
 'stem-root',
 'stem-surface',
 'stem-color',
 'veil-type',
 'veil-color',
 'has-ring',
 'ring-type',
 'spore-print-color',
 'habitat',
 'season']

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61069 entries, 0 to 61068
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   class                 61069 non-null  object
 1   cap-diameter          61069 non-null  float64
 2   cap-shape             61069 non-null  object
 3   cap-surface           46949 non-null  object
 4   cap-color             61069 non-null  object
 5   does-bruise-or-bleed  61069 non-null  object
 6   gill-attachment       51185 non-null  object
 7   gill-spacing          36006 non-null  object
 8   gill-color            61069 non-null  object
 9   stem-height           61069 non-null  float64
 10  stem-width            61069 non-null  float64
 11  stem-root             9531 non-null   object
 12  stem-surface          22945 non-null  object
 13  stem-color            61069 non-null  object
 14  veil-type             3177 non-null   object
 15  veil-color            7413 non-null   object
 16  has-ring              61069 non-null  object
 17  ring-type             58598 non-null  object
 18  spore-print-color     6354 non-null   object
 19  habitat               61069 non-null  object
 20  season                61069 non-null  object
dtypes: float64(3), object(18)
memory usage: 9.8+ MB

In [8]:
df.isnull().sum()

class                       0
cap-diameter                0
cap-shape                   0
cap-surface             14120
cap-color                   0
does-bruise-or-bleed        0
gill-attachment          9884
gill-spacing            25063
gill-color                  0
stem-height                 0
stem-width                  0
stem-root               51538
stem-surface            38124
stem-color                  0
veil-type               57892
veil-color              53656
has-ring                    0
ring-type                2471
spore-print-color       54715
habitat                     0
season                      0
dtype: int64

In [10]:
cols = df.columns.tolist()

for col in cols:
    unique_count = df[col].nunique()
    print(f'{col} has {unique_count} unique values')

class has 2 unique values
cap-diameter has 2571 unique values
cap-shape has 7 unique values
cap-surface has 11 unique values
cap-color has 12 unique values
does-bruise-or-bleed has 2 unique values
gill-attachment has 7 unique values
gill-spacing has 3 unique values
gill-color has 12 unique values
stem-height has 2226 unique values
stem-width has 4630 unique values
stem-root has 5 unique values
stem-surface has 8 unique values
stem-color has 13 unique values
veil-type has 1 unique values
veil-color has 6 unique values
has-ring has 2 unique values
ring-type has 8 unique values
spore-print-color has 7 unique values
habitat has 8 unique values
season has 4 unique values

In [11]:
for col in cols:
    unique_name = df[col].unique()
    print(f'{col} has {unique_name}')

class has ['p' 'e']
cap-diameter has [15.26 16.6  14.07 ... 22.85 21.8  20.42]
cap-shape has ['x' 'f' 'p' 'b' 'c' 's' 'o']
cap-surface has ['g' 'h' nan 't' 'y' 'e' 's' 'l' 'd' 'w' 'i' 'k']
cap-color has ['o' 'e' 'n' 'g' 'r' 'w' 'y' 'p' 'u' 'b' 'l' 'k']
does-bruise-or-bleed has ['f' 't']
gill-attachment has ['e' nan 'a' 'd' 's' 'x' 'p' 'f']
gill-spacing has [nan 'c' 'd' 'f']
gill-color has ['w' 'n' 'p' 'u' 'b' 'g' 'y' 'r' 'e' 'o' 'k' 'f']
stem-height has [16.95 17.99 17.8  ...  1.23  1.16  0.  ]
stem-width has [17.09 18.19 17.74 ... 32.59 30.99 30.51]
stem-root has ['s' nan 'b' 'r' 'c' 'f']
stem-surface has ['y' nan 's' 'k' 'i' 'h' 't' 'g' 'f']
stem-color has ['w' 'y' 'n' 'u' 'b' 'l' 'r' 'p' 'e' 'k' 'g' 'o' 'f']
veil-type has ['u' nan]
veil-color has ['w' 'y' nan 'n' 'e' 'u' 'k']
has-ring has ['t' 'f']
ring-type has ['g' 'p' 'e' 'l' 'f' 'm' nan 'r' 'z']
spore-print-color has [nan 'w' 'p' 'k' 'r' 'u' 'n' 'g']
habitat has ['d' 'm' 'g' 'h' 'l' 'p' 'w' 'u']
season has ['w' 'u' 'a' 's']

In [12]:
# List of columns to drop
cols_to_drop = ['stem-root', 'spore-print-color', 'veil-color', 'stem-surface']

# Drop them from the dataset
df = df.drop(columns=cols_to_drop)

In [13]:
df.head()

,class,cap-diameter,cap-shape,cap-surface,cap-color,does-bruise-or-bleed,gill-attachment,gill-spacing,gill-color,stem-height,stem-width,stem-color,veil-type,has-ring,ring-type,habitat,season
0,p,15.26,x,g,o,f,e,NaN,w,16.95,17.09,w,u,t,g,d,w
1,p,16.60,x,g,o,f,e,NaN,w,17.99,18.19,w,u,t,g,d,u
2,p,14.07,x,g,o,f,e,NaN,w,17.80,17.74,w,u,t,g,d,w
3,p,14.17,f,h,e,f,e,NaN,w,15.77,15.98,w,u,t,p,d,w
4,p,14.64,x,h,o,f,e,NaN,w,16.53,17.20,w,u,t,p,d,w

In [17]:
# Check number of duplicates
print("Duplicates found:", df.duplicated().sum())

# View some duplicate rows
df[df.duplicated()].head()

Duplicates found: 146

,class,cap-diameter,cap-shape,cap-surface,cap-color,does-bruise-or-bleed,gill-attachment,gill-spacing,gill-color,stem-height,stem-width,stem-color,veil-type,has-ring,ring-type,habitat,season
9863,p,1.14,x,g,w,f,a,d,w,3.13,1.78,e,NaN,f,f,d,u
12978,p,0.72,x,g,y,f,NaN,NaN,y,3.51,0.77,y,NaN,f,f,d,u
56526,p,4.27,o,s,n,f,NaN,c,w,0.00,0.00,f,NaN,f,f,d,u
56533,p,4.29,o,t,w,f,NaN,c,w,0.00,0.00,f,NaN,f,f,d,u
56576,p,4.59,o,s,w,f,NaN,c,w,0.00,0.00,f,NaN,f,f,d,u

#### They’re not real duplicates, they have different numeric values and other categorical values. Therefore, they are not exact duplicates and were retained for training.